cursor #e6f0ff
cursor_text_color #ffffff

foreground            #e6f0ff
background            #000000
selection_foreground  #000000
selection_background  #999999
url_color             #fcfc03

color0   #000000
color1   #ff1e00
color2   #20fc02
color3   #ffd700
color4   #efef00
color5   #747400
color6   #fcfc03
color7   #ffffe0
color8   #a3a38b
color9   #ff5842
color10  #63ff4e
color11  #ffe34e
color12  #ffff28
color13  #ffff4e
color14  #ffff8d
color15  #fffff2
