-- Hyprland configuration (Lua) — https://wiki.hypr.land/Configuring/Start/

hl.config({ autogenerated = false })

-- DMS_STARTUP_BEGIN
hl.on("hyprland.start", function()
	hl.exec_cmd("dbus-update-activation-environment --systemd --all")
	hl.exec_cmd("systemctl --user start hyprland-session.target")
end)
-- DMS_STARTUP_END

hl.config({
	input = {
		kb_layout = "us",
		kb_options = "lv3:ralt_switch",
		kb_variant = "altgr-intl",
		numlock_by_default = true,
		follow_mouse = 1,
		touchpad = {
			tap_to_click = true,
			natural_scroll = true,
		},
	},
	general = {
		gaps_in = 5,
		gaps_out = 5,
		border_size = 2,
		layout = "dwindle",
	},
	decoration = {
		rounding = 12,
		active_opacity = 0.85,
		inactive_opacity = 0.5,
		shadow = {
			enabled = true,
			range = 30,
			render_power = 5,
			offset = "0 5",
			color = "rgba(00000070)",
		},
		
		blur = {
			enabled = true,
			size = 6,
			passes = 3,

			noise = 0.02,
            contrast = 0.9,
            vibrancy = 0.3,
            vibrancy_darkness = 0.7,
		},
	},
	misc = {
		disable_hyprland_logo = true,
		disable_splash_rendering = true,
	},
	dwindle = {
		preserve_split = true,
	},
	master = {
		mfact = 0.5,
	},
})

hl.animation({ leaf = "windowsIn", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 5, bezier = "default" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 4, bezier = "default" })
hl.animation({ leaf = "fade", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 3, bezier = "default" })

hl.window_rule({ match = { class = "^(org\\.wezfurlong\\.wezterm)$" }, tile = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.)" }, rounding = 12 })
hl.window_rule({ match = { class = "^(gnome-control-center)$" }, tile = true })
hl.window_rule({ match = { class = "^(pavucontrol-qt)$" }, tile = true })
hl.window_rule({ match = { class = "^(nm-connection-editor)$" }, tile = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.Calculator)$" }, float = true })
hl.window_rule({ match = { class = "^(gnome-calculator)$" }, float = true })
hl.window_rule({ match = { class = "^(galculator)$" }, float = true })
hl.window_rule({ match = { class = "^(blueman-manager)$" }, float = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.Nautilus)$" }, float = true })
hl.window_rule({ match = { class = "^(xdg-desktop-portal)$" }, float = true })
hl.window_rule({ match = { class = ".*osu.*" }, immediate = true })
hl.window_rule({
	match = { class = "^(steam)$", title = "^(notificationtoasts)" },
	no_initial_focus = true,
	pin = true,
})
hl.window_rule({
	match = { class = "^(zen)$", title = "^(Picture-in-Picture)$" },
	float = true,
	opacity = "0.9 override",
})
hl.window_rule({
	match = { class = "^(vesktop)$", initial_title = "^(Discord Popout)$" },
	float = true,
	opacity = "0.9 override",
})
hl.window_rule({ match = { class = "^(zoom)$" }, float = true })
hl.window_rule({
	match = { class = "steam_app_\\d+" },
	opacity = "1 override",
	workspace = "3",
})

hl.window_rule({
	match = { title = "^(Teclado en pantalla de Steam Input)$"},
	opacity = "0.8 override"
})
hl.on("window.close", function(w)
    if w and w.class and string.match(w.class, "^steam_app_%d+$") then
        -- Wait 50ms to allow the window to fully vanish from the compositor tree
        hl.timer(function()
            local remaining_steam_apps = 0
            
            -- Get a list of all active windows across the system
            local windows = hl.get_windows()
            
            for _, win in ipairs(windows) do
                if win.class and string.match(win.class, "^steam_app_%d+$") then
                    remaining_steam_apps = remaining_steam_apps + 1
                end
            end
            
            -- Only switch to workspace 5 if NO other matching Steam apps remain open
            if remaining_steam_apps == 0 then
                hl.dispatch(hl.dsp.focus({workspace = 5}))
            end
        end, { timeout = 50, type = "oneshot" })
    end
end)


-- DMS windows floating by default
-- ! Hyprland doesn't size these windows correctly so disabling by default here
-- hl.window_rule({ match = { class = "^(org.quickshell)$" }, float = true })

hl.layer_rule({ match = { namespace = "^(quickshell)$" }, no_anim = true })
hl.layer_rule({ match = { namespace = "^dms:.*" }, no_anim = true })

require("dms.colors")
require("dms.outputs")
require("dms.layout")
require("dms.cursor")
require("dms.binds")
require("dms.binds-user")
require("dms.windowrules")
