-- Auto-generated by DMS — do not edit manually

hl.env("HYPRCURSOR_THEME", "Plasma-Overdose")
hl.env("XCURSOR_THEME", "Plasma-Overdose")
hl.env("HYPRCURSOR_SIZE", "28")
hl.env("XCURSOR_SIZE", "28")

hl.config({
	cursor = {
		no_hardware_cursors = 1,
		inactive_timeout = 2,
	},
})
